SELECT 
  T.TABSCHEMA AS "Schema",
  T.TABNAME AS "Table Name",
  C.COLNAME AS "Column Name",
  C.TYPENAME AS "Data Type",
  C.LENGTH AS "Length",
  C.REMARKS AS "Description",
  R.TABNAME AS "Referenced Table",
  RC.COLNAME AS "Referenced Column"
FROM 
  SYSCAT.TABLES T
INNER JOIN 
  SYSCAT.COLUMNS C ON T.TABSCHEMA = C.TABSCHEMA AND T.TABNAME = C.TABNAME
LEFT JOIN 
  SYSCAT.REFERENCES R ON T.TABSCHEMA = R.FK_TABSCHEMA AND T.TABNAME = R.FK_TABNAME
LEFT JOIN 
  SYSCAT.KEYCOLUSE RC ON R.PK_TABSCHEMA = RC.TABSCHEMA AND R.PK_TABNAME = RC.TABNAME AND R.PK_COLNAMES = RC.COLNAME
WHERE 
  T.TABSCHEMA = 'DCRGTIOP'
ORDER BY 
  T.TABNAME, C.COLNO;
